[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

# filer
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'source $CONFIG/fern.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
colorscheme gruvbox
set background=dark
highlight SignColumn ctermbg=NONE
'''

[[plugins]]
repo = 'lambdalisue/mr.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'voldikss/vim-floaterm'
hook_add = '''
let g:floaterm_width=0.8
let g:floaterm_height=0.8
augroup floaterm
autocmd!
autocmd FileType floaterm call s:floaterm_settings()
function! s:floaterm_settings() abort
" tnoremap <silent> <C-c> <C-\><C-n>:FloatermHide<CR>
endfunction
nnoremap <Leader>lg :FloatermNew lazygit<CR>
'''
