[[plugins]]
repo = 'nvim-neo-tree/neo-tree.nvim'
lua_add = 'require("config.neo-tree")'

[[plugins]]
repo = 'numToStr/Comment.nvim'
lua_add = 'require("Comment").setup()'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_add = '''
colorscheme nightfox
'''

[[plugins]]
repo = 'cohama/lexima.vim'
hook_source = '''
let g:lexima_ctrlh_as_backspace=1
'''

[[plugins]]
repo = 'voldikss/vim-floaterm'
hook_source = '''
let g:floaterm_borderchars='─│─│╭╮╯╰'
'''
hook_add = '''
command! Lg FloatermNew --name=lazygit --width=0.9 --height=0.9 --autoclose=2 lazygit
nnoremap <Leader>lt <Cmd>Lg<CR>
nnoremap <Leader>T <Cmd>FloatermNew --width=0.9 --height=0.9 --autoclose=2<CR>
nnoremap <Leader>trt <Cmd>FloatermNew --width=0.3 --height=0.5 --autoclose=2 --position=topright<CR>
nnoremap <Leader>trb <Cmd>FloatermNew --width=0.3 --height=0.5 --autoclose=2 --position=bottomright<CR>
function! s:set_floaterm_map() abort
  nnoremap <buffer> <silent> q <Cmd>FloatermHide<CR>
endfunction
autocmd User FloatermOpen call s:set_floaterm_map()
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'monaqa/dial.nvim'
lua_add = 'require("config.dial")'

[[plugins]]
repo = 'stevearc/aerial.nvim'
lua_add = 'require("config.aerial")'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
lua_add = 'require("config.gitsigns")'

[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_source = '''
let g:sonictemplate_vim_template_dir = '$HOME/.config/template'
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
lua_add = 'require("config.lualine")'

[[plugins]]
repo = 'folke/noice.nvim'
depends = ['nui.nvim', 'nvim-notify']
lua_add = 'require("config.noice")'

[[plugins]]
repo = 'rcarriga/nvim-notify'
lua_add = 'require("config.nvim-notify")'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'shutils/ChatGPT.nvim'
depends = ['nui.nvim', 'plenary.nvim', 'telescope.nvim']
lua_add = 'require("config.ChatGPT")'

[[plugins]]
repo = 'lambdalisue/gin.vim'

[[plugins]]
repo = 'lambdalisue/mr.vim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'mason.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_source = 'mason.nvim'

[[plugins]]
repo = 'williamboman/mason.nvim'
depends = ['mason-lspconfig.nvim', 'nvim-lspconfig']
on_event = 'VimEnter'
lua_post_source = 'require("config.mason")'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
lua_add = 'require("config.treesitter")'
hook_done_update = '''
TSUpdate
'''

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
lua_add = 'require("config.toggleterm")'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
lua_add = '''
require('nvim-web-devicons').setup({
  strict = true,
  override_by_filename = {
    ["docker-compose.yml"] = {
      icon = "",
      color = "#458ee6",
      cterm_color = "68",
      name = "Dockerfile",
    },
    ["docker-compose.yaml"] = {
      icon = "",
      color = "#458ee6",
      cterm_color = "68",
      name = "Dockerfile",
    },
    [".dockerignore"] = {
      icon = "",
      color = "#458ee6",
      cterm_color = "68",
      name = "Dockerfile",
    },
    ["dockerfile"] = {
      icon = "",
      color = "#458ee6",
      cterm_color = "68",
      name = "Dockerfile",
    },
  },
  override_by_extension = {
    ["svg"] = {
      icon = "",
      color = "#458ee6",
      cterm_color = "68",
      name = "Svg",
    },
    ["log"] = {
      icon = "",
      color = "#458ee6",
      cterm_color = "68",
      name = "Log",
    },
    ["txt"] = {
      icon = "",
      color = "#458ee6",
      cterm_color = "68",
      name = "Txt",
    },
  }
})
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'akinsho/bufferline.nvim'
hook_source = '''
set termguicolors
'''
lua_add = '''
require("config.bufferline")
'''

[[plugins]]
repo = 'uga-rosa/translate.nvim'
hook_add = '''
nnoremap <silent> <Leader>tl V:Translate JA<CR>
nnoremap <silent> <Leader>tw viw:Translate JA<CR>
vnoremap <silent> <Leader>tl :Translate JA<CR>
'''
lua_add = 'require("config.translate")'

[[plugins]]
repo = 'vim-denops/denops.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'xiyaowong/nvim-cursorword'
lua_add = 'vim.api.nvim_command("hi default CursorWord cterm=underline gui=underline")'
